### ISSUE TITLE
Current Value of Shares Uncalculated

### ISSUE THREAD

**Issue by jcscott2015** [Gnucash/gnucash-on-osx#4]
I'm using gnucash on a Mac, but this issue may affect all flavors of gnucash 3.1. 

When viewing a shares account ledger, like a mutual fund or a stock, the current value displayed on the bottom left of the page is just the number of shares with a dollar sign in front. The actual dollar value isn't calculated. I've attached a screen shot.

The dollar value is correctly calculated in the Accounts list subsections, so the method is there. It's just not hooked up in the ledger view.

![screen shot 2018-06-09 at 11 48 43 am](https://user-images.githubusercontent.com/14879921/41195079-d6039fdc-6bdb-11e8-92a4-829ac30517d5.png)
![screen shot 2018-06-09 at 11 55 17 am](https://user-images.githubusercontent.com/14879921/41195095-0dcc399c-6bdc-11e8-9af4-1f8057fd07a5.png)

**Comment by jralls** [comment]
A) You're in the wrong project. This project is about the build system for creating an environment in which to build the Mac Application Bundle.
B) We don't use the Github issue system for tracking bugs. Please see the [FAQ](https://wiki.gnucash.org/wiki/FAQ#Q:_I_think_I_found_a_bug._How_do_I_report_it.3F) for instructions on bug reporting.
C) This has already been [reported and fixed](https://bugzilla.gnome.org/show_bug.cgi?id=796409).
